image: fedora:latest

stages:
    - build
    - deploy

setup:
    stage: setup
    script:
        - sudo dnf -y install git
        - git clone https://github.com/dasch124/modeller
        - cd modeller
        - chmod u+x build.sh
        - ./build.sh -a setup
        - ./build.sh -i model.xml -a generateDocs -k -p showProperties=true
    artifacts:
      paths:
        - "."
      untracked: false
      expire_in: 30 days

pages:
  needs:
    - generate
  stage: deploy
  script:
    - mv modelFull.xml.html index.html 
    - mkdir .public
    - cp -r *.html .public
    - cp -r *.docx .public
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
